### ISSUE TITLE
I need help to understand

### ISSUE THREAD

**Issue by yppdr** [mariosimao/notion-sdk-php#113]
Hi there !
I start in php and I try to make the "sdk" work but I can't install it.
Indeed I am word for word the doc but when executing the command I have this error:

![image](https://user-images.githubusercontent.com/1734599/185766422-61e0a482-ba42-4c18-917a-7dad702dbc05.png)

Can anyone help me understand or have an example for me?

Thanks in advance

**Comment by mariosimao** [comment]
You need to install a package that implements `psr/http-client`. 

For example, run before installing the SDK.

```bash
composer require guzzlehttp/guzzle
```

I will update the documentation later to make this easier to understand.
