### ISSUE TITLE
Inlide databases

### ISSUE THREAD

**Issue by mariosimao** [mariosimao/notion-sdk-php#119]
Ref: https://developers.notion.com/changelog/changes-for-june-6-june-20-2022

**Comment by mariosimao** [comment]
Hi @philippe-pixieset . Thanks for your interest.

I would suggest leaving it outside the `create` method. 

Maybe two new methods:
- `enableInline()`
- `disableInline()`

See `changeCover` for reference.

PRs are welcome :) don't forget to run `composer test`.

**Comment by philippe-pixieset** [comment]
I'll open a PR asap! And great job on the package and the docs, by the way, it's super helpful and intuitive to use.
