### ISSUE TITLE
No support for Status type in Database

### ISSUE THREAD

**Issue by simondotws** [mariosimao/notion-sdk-php#130]
Fatal error: Uncaught Exception: Invalid property type: 'status' in .../mariosimao/notion-sdk-php/src/Databases/Properties/Factory.php:34 Stack trace: #0

Type:

`        "Status": {
            "id": "xxx",
            "type": "status",
            "status": {
                "id": "xxx",
                "name": "Accepted",
                "color": "green"
            }
}`

**Comment by simondotws** [comment]
@mariosimao that's awesome, looking forward to it!

**Comment by mariosimao** [comment]
@simondotws support to Status properties has been added to `v1.0.0-beta.2`.

Notice that the Notion API does support adding or updating Status properties on databases. Changing the status of page works fine.

Many breaking changes were introduced in v1. If you get stuck, do not hesitate to contact me.
