### ISSUE TITLE
[BUG]  Undefined functions with Query class

### ISSUE THREAD

**Issue by champsupertramp** [mariosimao/notion-sdk-php#139]
**Describe the bug**
I just copied the code from https://mario.engineering/notion-sdk-php/how-to/query-database.html
and it returns the `Call to undefined method Notion\Databases\Query::withFilter()`

This alone `Query::create()` works.

**Environment (please complete the following information):**
 - OS:  Mac OS
 - SDK Version v1.0.0

**Comment by champsupertramp** [comment]
Below works:

```   
$query = Query::create()
        ->changeSorts(
            Sort::property("Created time")->ascending()
        )
        ->changePageSize( 35 )
        ->changeFilter(
            CompoundFilter::and(
            TextFilter::property("URL")->contains("123")
            )
        );
```

**Comment by mariosimao** [comment]
Hello @champsupertramp, thanks for using `notion-sdk-php`!

On v1, all `->with...()` methods were renamed to `->change...()`. It seems that I forgot to update the documentation accordingly.

Thanks for pointing this out and I fill fix it soon.

**Comment by FFirmenich** [comment]
this made me stumble as well. Thanks for the nice SDK but the begin was a little bit misleading

**Comment by mariosimao** [comment]
@champsupertramp and @FFirmenich thank you for your feedback!

[Version 1.1.0](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.1.0) just got released with fixes on the [documentation](https://mario.engineering/notion-sdk-php/how-to/query-database.html) and other small improvements.

I am curious about how you use the SDK, what needs improvements and what additions you would like to enhance your development experience.

**Comment by champsupertramp** [comment]
Hi @mariosimao  sorry for bumping this issue. The `hasMore()` and `nextCursor()` also throw errors. 

The following properties work instead:

`$result->hasMore`
`$result->nextCursor`

**Comment by mariosimao** [comment]
@champsupertramp thanks for reporting.

Documentation has been fixed.
