### ISSUE TITLE
Use `azjezz/psl` instead of `beberlei/assert`

### ISSUE THREAD

**Issue by mariosimao** [mariosimao/notion-sdk-php#14]
You might want to use `azjezz/psl` for improved type inference, in future: I've used `beberlei/assert` and `webmozart/assert` extensively over the years, but @azjezz's work is just so much better, long-term

_Originally posted in https://github.com/mariosimao/notion-sdk-php/pull/6#discussion_r744172069_

**Comment by azjezz** [comment]
for reference, you can look at https://github.com/Roave/BackwardCompatibilityCheck/pull/306 and https://github.com/laminas/automatic-releases/pull/138
