### ISSUE TITLE
Properties are not nullable, in Notion Databases they are indeed

### ISSUE THREAD

**Issue by FFirmenich** [mariosimao/notion-sdk-php#147]
Queries to Databases fail if the Database has empty entries for different properties.

For me this happend for example for Date, Number and Url.

Either the Properties should be nullable (my favorite) or this can be catched with a default value that is defined per property (this way we would imply some values which could cause confusion to users).
I helped myself by adjusting the "fromArray" methods of those properties on my local copy for now.

without those adjustments it's not possible to query a database with empty cells

Examples below:
url:
![grafik](https://user-images.githubusercontent.com/3333743/211550720-4cbfdec9-bdb4-4e9a-a8ca-f7c748654bbc.png)
date:
![grafik](https://user-images.githubusercontent.com/3333743/211551023-4fbb69ac-7f71-490d-8573-576c7a398d41.png)
number:
![grafik](https://user-images.githubusercontent.com/3333743/211551066-2162d011-f96a-4216-b329-383e1195a0ac.png)

**Comment by mariosimao** [comment]
Hi @FFirmenich! Thanks for the feedback again.

Nullable page properties were introduced on [v1.2.0](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.2.0) and are already available for usage.

Also, the SDK now supports `Relation` database properties.
