### ISSUE TITLE
[BUG] Fatal Error when updating properties of a page

### ISSUE THREAD

**Issue by champsupertramp** [mariosimao/notion-sdk-php#158]
**Describe the bug**
The following code snippet throws errors when updating page properties:
```
        $notion_id = $request['notion_id'];
        $page = $notion->pages()->find($notion_id);

        $lastEditedTime = \Notion\Pages\Properties\Date::create(new \DateTimeImmutable());
        $page = $page->addProperty("Last edited time", $lastEditedTime);

        $createdTime = \Notion\Pages\Properties\Date::create(new \DateTimeImmutable());
        $page = $page->addProperty("Created time", $createdTime);

        $status = \Notion\Pages\Properties\Status::fromID("ad200f50-4961-4fcb-a6e5-89f2fb2c6dd8");
        $page = $page->addProperty("Status", $status);
        
        $notion->pages()->update($page);
```

Errors:
<img width="663" alt="Screen Shot 2023-01-17 at 8 09 55 PM" src="https://user-images.githubusercontent.com/12200688/212895502-760b2058-509d-47ef-9427-a5eaad5a5ab3.png">

**Environment (please complete the following information):**
 - OS: [Macosx Monterey]
 - SDK Version [1.0]

**Comment by mariosimao** [comment]
Hi @champsupertramp! Thanks again for your feedback.

A [new version was released](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.3.0) that solves this issue.

**Comment by champsupertramp** [comment]
Hi @mariosimao  Thank you for the fixes. After updating to the latest version, the above issues no longer occur. But there's another issue with the latest version. The following error shows when updating the Status: 
```
Select option color doesn't match existing for ad200f50-4961-4fcb-a6e5-89f2fb2c6dd8
```

Here's the code:
```
$status = \Notion\Pages\Properties\Status::fromID("ad200f50-4961-4fcb-a6e5-89f2fb2c6dd8");
$page = $page->addProperty("Status", $status);
$notion->pages()->update($page);
```

**Comment by mariosimao** [comment]
I look like Notion API does not support updating page status properties color. I am looking on how to solve this issue on the SDK.

In the meanwhile, you could explicitly set the color:

```php
$status = Status::fromId("ad200f50-4961-4fcb-a6e5-89f2fb2c6dd8")
    ->changeColor(Color::Green); // Set your color here
$page = $page->addProperty("Status", $status);
$notion->pages()->update($page);
```

**Comment by champsupertramp** [comment]
Hi @champsupertramp Thank you - it changes the status now after adding the color that matches the Status ID.

**Comment by champsupertramp** [comment]
Hi @mariosimao, I noticed the app I use for requests to the API. Whenever I update a property, it shows the "Last Edited By" as the App name, and then after a few hours, it changes to the user I used to change the property with their notion account ID.

**Comment by mariosimao** [comment]
@champsupertramp could you tell me what app is this? I am curious about how they managed to update this property via API.
