### ISSUE TITLE
[BUG] Allow updating select property without color

### ISSUE THREAD

**Issue by champsupertramp** [mariosimao/notion-sdk-php#164]
**Describe the bug**
The following doesn't allow you to update a Status property with only an ID:

```
 $status = \Notion\Pages\Properties\Status::fromID( $status_id );
```

This works
```
$status_id = "testtest";
$status = \Notion\Pages\Properties\Status::fromID( $status_id );->changeColor(\Notion\Common\Color::Blue);
```

Currently, you need the Color and Status ID to update a status. You need to match the status ID and the color.

**Comment by champsupertramp** [comment]
I also tried concatenating the class and method but it throws the following:

```
Cannot instantiate enum Notion\\Common\\Color
```

I'm trying to do the following:
```
$classColor = "\Notion\Common\Color";
$color = "red";
$thecolor = new $classColor;
$status = \Notion\Pages\Properties\Status::fromID( $status_id )->changeColor(call_user_func($thecolor,"::".ucfirst($color)));

```

**Comment by mariosimao** [comment]
Thanks again for your feedback, @champsupertramp :)

> Currently, you need the Color and Status ID to update a status. You need to match the status ID and the color.


Yes, this is something that was also mentioned in [this other issue](https://github.com/mariosimao/notion-sdk-php/issues/158#issuecomment-1387133067).

Luckily, I found a solution and will release a new version soon that will allow updating status properties without informing the color.


> ```
> $color = "red";
> $classColor = "\Notion\Common\Color";
> $thecolor = constant( $classColor."::".ucfirst($color) );
> $status = \Notion\Pages\Properties\Status::fromID( $status_id )->changeColor( $thecolor  );
> ```

I think there are better ways to instantiate an enum:

1. If you already know the color:

```php
$color = Color::Red;
```
2. From a string:
```php
$colorString = "Red",
$color = Color::from($colorString);
```

3. Safely from a string
```php
$colorString = "Invalid color";
$color = Color::tryFrom($colorString) ?? Color::Default;
```

**Comment by mariosimao** [comment]
[Version 1.4.0 was released](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.4.0) and allows updating a status option without setting the color.

1. From option ID:
    ```php
    $status = Status::fromId("dffb45fc-4126-413d-8439-4bb13c89e88c");
    $page = $page->addProperty("Status", $status);
    ```

2. From option name:
    ```php
    $status = Status::fromName("Done");
    $page = $page->addProperty("Status", $status);
    ```

6. From option object:
    ```php
    $database = $notion->database()->find($databaseId);
    $options = $database->properties["Status"];
    $myOption = $options[0];

    $status = Status::fromOption($myOption);
    $page = $page->addProperty("Status", $status);
    ```

**Comment by champsupertramp** [comment]
Hi @mariosimao thank you for your response and great work!

**Comment by youvalteboul** [comment]
Hi @mariosimao,

I've tried all the suggestions but nothing works
I always get the same error.

i'm on version `1.8.0` (I also tried on version `1.4.0`)

```
$status = Status::fromId("STATUS_ID")
    ->changeColor(Color::Purple);

$page = $page->addProperty("Status", $status);

$this->notion->pages()->update($page);
```


error

```
body failed validation. Fix one:
body.properties.Created time.title should be defined, instead was `undefined`.
body.properties.Created time.rich_text should be defined, instead was `undefined`.
body.properties.Created time.number should be defined, instead was `undefined`.
body.properties.Created time.url should be defined, instead was `undefined`.
body.properties.Created time.select should be defined, instead was `undefined`.
body.properties.Created time.multi_select should be defined, instead was `undefined`.
body.properties.Created time.people should be defined, instead was `undefined`.
body.properties.Created time.email should be defined, instead was `undefined`.
body.properties.Created time.phone_number should be defined, instead was `undefined`.
body.properties.Created time.date should be defined, instead was `undefined`.
body.properties.Created time.checkbox should be defined, instead was `undefined`.
body.properties.Created time.relation should be defined, instead was `undefined`.
body.properties.Created time.files should be defined, instead was `undefined`.
body.properties.Created time.status should be defined, instead was `undefined`.
body.properties.Who's interested?.type should be not present, instead was `"multi_select"`.
body.properties.Who's interested?.multi_select should be not present, instead was `[]`.
body.properties.Who's interested?.name should be defined, instead was `undefined`.
body.properties.Who's interested?.start should be defined, instead was `undefined`.
```

**Comment by youvalteboul** [comment]
> > Hi @mariosimao,
> > I've tried all the suggestions but nothing works
> > I always get the same error.
> > i'm on version `1.8.0` (I also tried on version `1.4.0`)
> > ```
> > $status = Status::fromId("STATUS_ID")
> >     ->changeColor(Color::Purple);
> > 
> > $page = $page->addProperty("Status", $status);
> > 
> > $this->notion->pages()->update($page);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error
> > ```
> > body failed validation. Fix one:
> > body.properties.Created time.title should be defined, instead was `undefined`.
> > body.properties.Created time.rich_text should be defined, instead was `undefined`.
> > body.properties.Created time.number should be defined, instead was `undefined`.
> > body.properties.Created time.url should be defined, instead was `undefined`.
> > body.properties.Created time.select should be defined, instead was `undefined`.
> > body.properties.Created time.multi_select should be defined, instead was `undefined`.
> > body.properties.Created time.people should be defined, instead was `undefined`.
> > body.properties.Created time.email should be defined, instead was `undefined`.
> > body.properties.Created time.phone_number should be defined, instead was `undefined`.
> > body.properties.Created time.date should be defined, instead was `undefined`.
> > body.properties.Created time.checkbox should be defined, instead was `undefined`.
> > body.properties.Created time.relation should be defined, instead was `undefined`.
> > body.properties.Created time.files should be defined, instead was `undefined`.
> > body.properties.Created time.status should be defined, instead was `undefined`.
> > body.properties.Who's interested?.type should be not present, instead was `"multi_select"`.
> > body.properties.Who's interested?.multi_select should be not present, instead was `[]`.
> > body.properties.Who's interested?.name should be defined, instead was `undefined`.
> > body.properties.Who's interested?.start should be defined, instead was `undefined`.
> > ```
> 
> @youvalteboul, could you try to add the status without setting the color? Color is defined automatically on Notion based on the status options from the Database column.

i have the same error
