### ISSUE TITLE
[BUG]  Call to undefined method Notion\\Pages\\Page::getProperty()

### ISSUE THREAD

**Issue by champsupertramp** [mariosimao/notion-sdk-php#168]
**Describe the bug**

When I'm trying to add a Person, it throws this error: 

```
Call to undefined method Notion\\Pages\\Page::getProperty()
```

I'm following this tutorial: https://mario.engineering/notion-sdk-php/page-properties/People.html

Here's my code:
```
$page = $notion->pages()->find( $notion_id) ;
$user = $notion->users()->find( $account_id );

$assignees = $page->getProperty("Person");

$new_person = \Notion\Pages\Properties\People::create($user);

$assignees = $assignees->addProperty("Person", $new_person);

$page = $page->addProperty("Person", $assignees );
```

**Comment by champsupertramp** [comment]
I've upgraded from ` mariosimao/notion-sdk-php (v1.3.0 => v1.4.0)`

**Comment by mariosimao** [comment]
It seems that I made a typo on the class method.

Unfortunately I am on vacation without my computer and I won't be able to fix it before March.

Proposed solutions:

- You could open a simple PR fixing the typo.
- Use the misspelled method `getProprety`.

**Comment by champsupertramp** [comment]
Hi @mariosimao, Thanks for letting me know. I just created a pull request to fix the typo. 

Have a great vacation. Take good care

**Comment by mariosimao** [comment]
@champsupertramp, thanks again for your contribution. A [new version](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.4.1) is now available where the typo is fixed.
