### ISSUE TITLE
[FEATURE] Notion blocks to markdown or html?

### ISSUE THREAD

**Issue by wassim** [mariosimao/notion-sdk-php#197]
Is there any plans to add a list of blocks to markdown/html kind of converter? Something like https://github.com/souvikinator/notion-to-md

**Comment by mariosimao** [comment]
This should be the next feature of the SDK. However, I do not have a deadline in mind.

**Comment by mariosimao** [comment]
@wassim I've developed the base structure for converting Notion blocks to Markdown.

I'm currently adding tests for this new feature, but if you already wants to use it:

```bash
$ composer require mariosimao/notion-sdk-php:dev-markdown
```

Usage example:

```php
<?php

require "vendor/autoload.php";

use Notion\Blocks\Renderer\MarkdownRenderer;
use Notion\Notion;

$token = "secret_token";
$notion = Notion::create($token);

$pageId = "page_id";
$blocks = $notion->blocks()->findChildrenRecursive($pageId);

echo PHP_EOL;
echo MarkdownRenderer::render(...$blocks);
```

**Comment by jacquesbh** [comment]
That feature could be then mixed with a Markdown to HTML converter as well, like https://commonmark.thephpleague.com/.

Thank you! I'll try to test it out soon.

**Comment by mariosimao** [comment]
@jacquesbh exactly. Formatting as Markdown should be enough. Converting to HTML may be out of scope of this library.

**Comment by mariosimao** [comment]
Dear @wassim and @jacquesbh,

A [new version](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.7.0) of the SDK was released containing formatting blocks as markdown.
