### ISSUE TITLE
[FEATURE] Use new `Empty` object instead of `stdClass`

### ISSUE THREAD

**Issue by mariosimao** [mariosimao/notion-sdk-php#200]
This is only an idea.

To be done: search all use cases of `stdClass`, mostly on JSON conversion.

SDK public API changes, should be released on v2.

**Comment by ddouble-d** [comment]
@mariosimao  did you mean instead of using ```new stdClass()```
will replace it to ```new {}``` instead?

**Comment by mariosimao** [comment]
@ddouble-d I think `new {}` is not a valid in PHP.

The idea was to create a new class called `Empty` which would convert JSON `{}` into an object. 

Honestly, I no longer think it is necessary. Thus, I am closing this issue.
