### ISSUE TITLE
[BUG] Search all pages with Query::all() is not working correctly

### ISSUE THREAD

**Issue by rickyheijnen** [mariosimao/notion-sdk-php#210]
**Describe the bug**
Search all pages is not working because the array is not correctly formatted as object ( { } ), but as a array ( [ ] ).

The response from the Notion API is:
`body failed validation: body should be an object, instead was `[]`.`

**Expected behavior**
Show a list of all pages

**Code snippet**
```
<?
$notion = Notion::create("access_code");
$query = Query::all();
$notion->search()->search($query);
?>
```

**Environment:**
 - SDK Version v1.6.2

**Comment by mariosimao** [comment]
Hi @rickyheijnen, thanks for reporting this bug!

I have fixed it and released a [new version](https://github.com/mariosimao/notion-sdk-php/releases/tag/v1.7.0) of the SDK.
