### ISSUE TITLE
Href links in Rich Text not working

### ISSUE THREAD

**Issue by Joseph-Azzam** [mariosimao/notion-sdk-php#242]
**Describe the bug**
Richtext URL are not displaying

**To Reproduce**
Here's my code
```
$page_block_text = RichText::fromString("LinkText");
$page_block_text = $page_block_text->changeHref("https://github.com");
array_push($page_block, $page_block_text);
$page_block = Paragraph::create()->changeText($page_block);
array_push($page_blocks, $page_block);
$Notion->blocks()->append($page->id, $page_blocks);
```

In a RichText JSON Block, there are two fields that mention a URL, one is href and the other is link->url

`
                    {
                        "plain_text": "LinkText",
                        "href": "https:\/\/google.com",
                        "annotations": {
                            "bold": true,
                            "italic": false,
                            "strikethrough": false,
                            "underline": false,
                            "code": false,
                            "color": "default"
                        },
                        "type": "text",
                        "text": {
                            "content": "LinkText",
                            "link": { 
                                "url": "https:\/\/google.com" 
                            }
                        }
                    }
`

--------------------
Found a fix, will submit

**Comment by mariosimao** [comment]
Fix available on v1.8.1
