### ISSUE TITLE
How to read  content in a tabpage

### ISSUE THREAD

**Issue by giulo** [mariosimao/notion-sdk-php#299]
Hi all,
i need to read the contet of a specifc tabpage inside a view
I post an image,i need to read the values in the colum "Referenza" inside  
ORDINI page
PREORDINI tab
Can you help me to code this?
Thanks
![immagine](https://github.com/mariosimao/notion-sdk-php/assets/38974203/ddc9a9ee-a4c5-4941-ac57-89ebdfd83df8)

**Comment by giulo** [comment]
I just used 
$query = Query::title("PREORDINI");

**Comment by mariosimao** [comment]
The Notion API does not support Database Views. Views, are basically parts of the database with columns and/or rows hidden.

To get the content of a database column, you could [list the database pages](https://mario.engineering/notion-sdk-php/how-to/list-database-pages.html).

If your view "PREORDINI" has a filter, you would need to replicate this filter while [querying the database](https://mario.engineering/notion-sdk-php/how-to/query-database.html).
