### ISSUE TITLE
Just a bit confused, why return a new class instead of returning the object itself? Is there any specific consideration?

### ISSUE THREAD

**Issue by yankewei** [mariosimao/notion-sdk-php#360]
https://github.com/mariosimao/notion-sdk-php/blob/a3d4c145c1705a5c5c24e3e5e93b45cc1f8cc130/src/Pages/Page.php#L173

**Comment by mariosimao** [comment]
To achieve immutability.

Reasoning: https://web.mit.edu/6.005/www/fa15/classes/09-immutability
