### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RostyslavYakuts** [mariosimao/notion-sdk-php#387]
Mistake in documentation:  https://mariosimao.github.io/notion-sdk-php/getting-started.html 
<?php

require "vendor/autoload.php";

use Notion\Notion;

$token = "secret_token";
$notion = Notion::create($token);

$users = $notion->users()->findAll();

foreach ($users as $user) {
    **echo $user->name . PHP_EOL;**
}
echo $user->name  leads to fatal error Cannot access private property Notion\Users\User::$name
 Your property in class User: **private string $name;**

**Comment by mariosimao** [comment]
Hello @RostyslavYakuts!

What version of the library are you using?

**Comment by RostyslavYakuts** [comment]
Hi @mariosimao 
`composer require mariosimao/notion-sdk-php
Using version ^0.6.2 for mariosimao/notion-sdk-php
./composer.json has been updated
Running composer update mariosimao/notion-sdk-php
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking mariosimao/notion-sdk-php (v0.6.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading mariosimao/notion-sdk-php (v0.6.2)
  - Installing mariosimao/notion-sdk-php (v0.6.2): Extracting archive
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
12 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
`
![screenshot_150](https://github.com/user-attachments/assets/74ce5552-89ff-45e8-88c5-e52aa002e35a)

**Comment by mariosimao** [comment]
Hello @RostyslavYakuts the documentation refers to the latest version of the SDK: v1.14.0

You are using a 2-year-old version which is no longer supported. I strongly recommend updating it.

**Comment by RostyslavYakuts** [comment]
ok, thanks
