### ISSUE TITLE
Simple Table block

### ISSUE THREAD

**Issue by mariosimao** [mariosimao/notion-sdk-php#66]
- https://developers.notion.com/changelog/simple-table-support
- https://developers.notion.com/reference/block#table-blocks

**Comment by ArondeParon** [comment]
Is there a workaround available to support tables? I have noticed they are cast to `Unknown` objects but it seems like the row properties are missing. Would be awesome if this can be supported!

**Comment by mariosimao** [comment]
@ArondeParon you should be able to access raw API data by using the `$block->toArray()` method. I will try to add support to Table blocks on my next developments.
