### ISSUE TITLE
How to retrieve pages from database

### ISSUE THREAD

**Issue by lewsid** [mariosimao/notion-sdk-php#75]
Does this API allow for the ability to return a set of pages from a given database? I can't seem to find any documentation or tests that handle this use-case. Perhaps I'm missing something?

**Comment by lewsid** [comment]
I appreciate the follow-up!

**Comment by mariosimao** [comment]
@lewsid,

Version 0.5.0 has been released, and now it is possible to query a database.

Simply listing all pages within a database: https://github.com/mariosimao/notion-sdk-php/blob/main/docs/how-to/list-database-pages.md

Advanced query: https://github.com/mariosimao/notion-sdk-php/blob/main/docs/how-to/query-database.md
