### ISSUE TITLE
Internal cover image is not supported

### ISSUE THREAD

**Issue by frederichoule** [mariosimao/notion-sdk-php#80]
Internal cover images are now supported by Notion API, as read-only fields. I think we should be able to retrieve pages with internal covers instead of throwing an exception.

**Comment by frederichoule** [comment]
Hey @mariosimao , have you had time to merge the PR? Thanks.

**Comment by mariosimao** [comment]
Sorry for the delay. Could you please submit the PR again?

**Comment by frederichoule** [comment]
Do you want me to remove the old test from my branch?

**Comment by mariosimao** [comment]
@frederichoule 

Thanks for your patience and contribution. The changes are now available on v0.5.1

**Comment by frederichoule** [comment]
Thanks @mariosimao
