### ISSUE TITLE
Unable to create RichText URL

### ISSUE THREAD

**Issue by NFarrington** [mariosimao/notion-sdk-php#88]
Hello, thanks for the great SDK 😁 

It doesn't currently appear possible to create a RichText object with a link to a URL that's correctly formatted as a clickable link.

As an example, I currently have this code:

```
BulletedListItem::create()->withText([
    RichText::createText("My link: "),
    RichText::createText("https://example.com/my-link"),
]));
```

It's not possible to use a `Text` object directly as BulletedListItem only accepts RichText. `https://example.com/my-link` isn't clickable in Notion, I guess because the underlying text object isn't a link object (https://developers.notion.com/reference/rich-text#link-objects).

It would be great to be able to do something like the following to make the link clickable:

```
BulletedListItem::create()->withText([
    RichText::createText("My link: "),
    RichText::createText("https://example.com/my-link")
        ->withUrl("https://example.com/my-link"),
]));
```

**Comment by mariosimao** [comment]
Hi @NFarrington! 

I am glad to know the SDK is helpful to you.

Indeed, the current version of this library does not support an approach to adding links.

I will continue the discussion on the PR.
